const nomes = [
    'Sophia',
    'Alice',
    'Julia',
    'Isabella',
    'Manuela',
    'Laura',
    'Luiza',
    'Valentina',
    'Giovanna',
    'Maria Eduarda',
    'Helena',
    'Beatriz',
    'Maria Luiza',
    'Lara',
    'Mariana',
    'Matheus',
    'Rafael',
    'Heitor',
    'Enzo',
    'Guilherme',
    'Nicolas',
    'Lorenzo',
    'Gustavo',
    'Felipe',
    'Samuel',
    'João',
    'Daniel',
    'Nicole',
    'Rafaela',
    'Heloísa',
    'Isadora',
    'Lívia',
    'Maria Clara',
    'Ana Clara',
    'Lorena',
    'Gabriela',
    'Yasmin',
    'Isabelly',
    'Sarah',
    'Ana Julia',
    'Letícia',
    'Ana Luiza',
    'João',
    'Bryan',
    'Joaquim',
    'João',
    'Thiago',
    'Antônio',
    'Davi',
    'Francisco',
    'Enzo',
    'Bruno',
    'Emanuel',
    'Melissa',
    'Marina',
    'Clara',
    'Cecília',
    'Esther',
    'Emanuelly',
    'Rebeca',
    'Ana Beatriz',
    'Lavínia',
    'Vitória',
    'Bianca',
    'Catarina',
    'Larissa',
    'Maria Fernanda',
    'Fernanda',
    'Amanda',
    'Alícia',
    'Carolina',
    'Agatha',
    'Gabrielly',
    'Miguel',
    'Davi',
    'Arthur',
    'Pedro',
    'Gabriel',
    'Bernardo',
    'Lucas',
    'Vitor',
    'Leonardo',
    'Henrique',
    'Theo',
    'Murilo',
    'Eduardo',
    'Pedro',
    'Pietro',
    'Cauã',
    'Isaac',
    'Caio',
    'Vinicius',
    'Benjamin',
    'João',
    'Lucca',
    'João',
    'Ian',
    'Davi',
    'Rodrigo',
    'Otávio',

];
const sobrenomes =[
    'Sossai',
    'Agrizzi',
    'De Angeli',
    'Ferreira',
    'Braga',
    'da Silva',
    'Zampirolli',
    'Della Coletta',
    'Fernandes',
    'Alves',
    'Costalonga',
    'Botteon',
    'Caliman',
    'de Oliveira',
    'Zanette',
    'Salvador',
    'Silva',
    'Zandonadi',
    'Pesca',
    'Falqueto',
    'Tosi',
    'da Costa',
    'de Souza',
    'Gomes',
    'Calmon',
    'Pereira',
    'Sossai detto Pegorer',
    'de Almeida',
    'Moreira',
    'de Jesus',
    'Martins',
    'Rodrigues',
    'Balarini',
    'Gonçalves',
    'Pizzol',
    'Vieira',
    'Breda',
    'Bazoni',
    'Corrêa',
    'Filete',
    'Oliveira',
    'Venturim',
    'Almeida',
    'dos Santos',
    'Falchetto',
    'Barbosa',
    'Scaramussa',
    'Partelli',
    'de Barros',
];

module.exports = class Helpers {

    static gerarNomeRandomico(){
        let indexNome = Math.floor(Math.random() * 100 + 1)
        let indexSobrenome = Math.floor(Math.random() * 50 + 1)
        

        return nomes[indexNome] + ' ' + sobrenomes[indexSobrenome];
    }
};